/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirmUsersRouteImport } from './routes/firm-users'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AiReviewRouteImport } from './routes/ai-review'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MattersIndexRouteImport } from './routes/matters.index'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as MattersIdRouteImport } from './routes/matters.$id'
import { Route as MattersIdIndexRouteImport } from './routes/matters.$id.index'
import { Route as IntakeIdIndexRouteImport } from './routes/intake.$id.index'
import { Route as MattersIdTimelineRouteImport } from './routes/matters.$id.timeline'
import { Route as MattersIdTasksRouteImport } from './routes/matters.$id.tasks'
import { Route as MattersIdOffersRouteImport } from './routes/matters.$id.offers'
import { Route as MattersIdNotesRouteImport } from './routes/matters.$id.notes'
import { Route as MattersIdDocumentsRouteImport } from './routes/matters.$id.documents'
import { Route as MattersIdDeadlinesRouteImport } from './routes/matters.$id.deadlines'
import { Route as IntakeIdAiReviewRouteImport } from './routes/intake.$id.ai-review'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmUsersRoute = FirmUsersRouteImport.update({
  id: '/firm-users',
  path: '/firm-users',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReviewRoute = AiReviewRouteImport.update({
  id: '/ai-review',
  path: '/ai-review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIndexRoute = MattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIdRoute = MattersIdRouteImport.update({
  id: '/matters/$id',
  path: '/matters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIdIndexRoute = MattersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MattersIdRoute,
} as any)
const IntakeIdIndexRoute = IntakeIdIndexRouteImport.update({
  id: '/intake/$id/',
  path: '/intake/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIdTimelineRoute = MattersIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => MattersIdRoute,
} as any)
const MattersIdTasksRoute = MattersIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => MattersIdRoute,
} as any)
const MattersIdOffersRoute = MattersIdOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => MattersIdRoute,
} as any)
const MattersIdNotesRoute = MattersIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => MattersIdRoute,
} as any)
const MattersIdDocumentsRoute = MattersIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MattersIdRoute,
} as any)
const MattersIdDeadlinesRoute = MattersIdDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => MattersIdRoute,
} as any)
const IntakeIdAiReviewRoute = IntakeIdAiReviewRouteImport.update({
  id: '/intake/$id/ai-review',
  path: '/intake/$id/ai-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-review': typeof AiReviewRoute
  '/command-center': typeof CommandCenterRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/firm-users': typeof FirmUsersRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/matters/$id': typeof MattersIdRouteWithChildren
  '/intake/': typeof IntakeIndexRoute
  '/matters/': typeof MattersIndexRoute
  '/intake/$id/ai-review': typeof IntakeIdAiReviewRoute
  '/matters/$id/deadlines': typeof MattersIdDeadlinesRoute
  '/matters/$id/documents': typeof MattersIdDocumentsRoute
  '/matters/$id/notes': typeof MattersIdNotesRoute
  '/matters/$id/offers': typeof MattersIdOffersRoute
  '/matters/$id/tasks': typeof MattersIdTasksRoute
  '/matters/$id/timeline': typeof MattersIdTimelineRoute
  '/intake/$id/': typeof IntakeIdIndexRoute
  '/matters/$id/': typeof MattersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-review': typeof AiReviewRoute
  '/command-center': typeof CommandCenterRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/firm-users': typeof FirmUsersRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/intake': typeof IntakeIndexRoute
  '/matters': typeof MattersIndexRoute
  '/intake/$id/ai-review': typeof IntakeIdAiReviewRoute
  '/matters/$id/deadlines': typeof MattersIdDeadlinesRoute
  '/matters/$id/documents': typeof MattersIdDocumentsRoute
  '/matters/$id/notes': typeof MattersIdNotesRoute
  '/matters/$id/offers': typeof MattersIdOffersRoute
  '/matters/$id/tasks': typeof MattersIdTasksRoute
  '/matters/$id/timeline': typeof MattersIdTimelineRoute
  '/intake/$id': typeof IntakeIdIndexRoute
  '/matters/$id': typeof MattersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-review': typeof AiReviewRoute
  '/command-center': typeof CommandCenterRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/firm-users': typeof FirmUsersRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/tasks': typeof TasksRoute
  '/matters/$id': typeof MattersIdRouteWithChildren
  '/intake/': typeof IntakeIndexRoute
  '/matters/': typeof MattersIndexRoute
  '/intake/$id/ai-review': typeof IntakeIdAiReviewRoute
  '/matters/$id/deadlines': typeof MattersIdDeadlinesRoute
  '/matters/$id/documents': typeof MattersIdDocumentsRoute
  '/matters/$id/notes': typeof MattersIdNotesRoute
  '/matters/$id/offers': typeof MattersIdOffersRoute
  '/matters/$id/tasks': typeof MattersIdTasksRoute
  '/matters/$id/timeline': typeof MattersIdTimelineRoute
  '/intake/$id/': typeof IntakeIdIndexRoute
  '/matters/$id/': typeof MattersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-review'
    | '/command-center'
    | '/deadlines'
    | '/documents'
    | '/firm-users'
    | '/login'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/matters/$id'
    | '/intake/'
    | '/matters/'
    | '/intake/$id/ai-review'
    | '/matters/$id/deadlines'
    | '/matters/$id/documents'
    | '/matters/$id/notes'
    | '/matters/$id/offers'
    | '/matters/$id/tasks'
    | '/matters/$id/timeline'
    | '/intake/$id/'
    | '/matters/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-review'
    | '/command-center'
    | '/deadlines'
    | '/documents'
    | '/firm-users'
    | '/login'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/intake'
    | '/matters'
    | '/intake/$id/ai-review'
    | '/matters/$id/deadlines'
    | '/matters/$id/documents'
    | '/matters/$id/notes'
    | '/matters/$id/offers'
    | '/matters/$id/tasks'
    | '/matters/$id/timeline'
    | '/intake/$id'
    | '/matters/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-review'
    | '/command-center'
    | '/deadlines'
    | '/documents'
    | '/firm-users'
    | '/login'
    | '/settings'
    | '/setup'
    | '/tasks'
    | '/matters/$id'
    | '/intake/'
    | '/matters/'
    | '/intake/$id/ai-review'
    | '/matters/$id/deadlines'
    | '/matters/$id/documents'
    | '/matters/$id/notes'
    | '/matters/$id/offers'
    | '/matters/$id/tasks'
    | '/matters/$id/timeline'
    | '/intake/$id/'
    | '/matters/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiReviewRoute: typeof AiReviewRoute
  CommandCenterRoute: typeof CommandCenterRoute
  DeadlinesRoute: typeof DeadlinesRoute
  DocumentsRoute: typeof DocumentsRoute
  FirmUsersRoute: typeof FirmUsersRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  TasksRoute: typeof TasksRoute
  MattersIdRoute: typeof MattersIdRouteWithChildren
  IntakeIndexRoute: typeof IntakeIndexRoute
  MattersIndexRoute: typeof MattersIndexRoute
  IntakeIdAiReviewRoute: typeof IntakeIdAiReviewRoute
  IntakeIdIndexRoute: typeof IntakeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firm-users': {
      id: '/firm-users'
      path: '/firm-users'
      fullPath: '/firm-users'
      preLoaderRoute: typeof FirmUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-review': {
      id: '/ai-review'
      path: '/ai-review'
      fullPath: '/ai-review'
      preLoaderRoute: typeof AiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/': {
      id: '/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof MattersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$id': {
      id: '/matters/$id'
      path: '/matters/$id'
      fullPath: '/matters/$id'
      preLoaderRoute: typeof MattersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$id/': {
      id: '/matters/$id/'
      path: '/'
      fullPath: '/matters/$id/'
      preLoaderRoute: typeof MattersIdIndexRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/intake/$id/': {
      id: '/intake/$id/'
      path: '/intake/$id'
      fullPath: '/intake/$id/'
      preLoaderRoute: typeof IntakeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/$id/timeline': {
      id: '/matters/$id/timeline'
      path: '/timeline'
      fullPath: '/matters/$id/timeline'
      preLoaderRoute: typeof MattersIdTimelineRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/matters/$id/tasks': {
      id: '/matters/$id/tasks'
      path: '/tasks'
      fullPath: '/matters/$id/tasks'
      preLoaderRoute: typeof MattersIdTasksRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/matters/$id/offers': {
      id: '/matters/$id/offers'
      path: '/offers'
      fullPath: '/matters/$id/offers'
      preLoaderRoute: typeof MattersIdOffersRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/matters/$id/notes': {
      id: '/matters/$id/notes'
      path: '/notes'
      fullPath: '/matters/$id/notes'
      preLoaderRoute: typeof MattersIdNotesRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/matters/$id/documents': {
      id: '/matters/$id/documents'
      path: '/documents'
      fullPath: '/matters/$id/documents'
      preLoaderRoute: typeof MattersIdDocumentsRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/matters/$id/deadlines': {
      id: '/matters/$id/deadlines'
      path: '/deadlines'
      fullPath: '/matters/$id/deadlines'
      preLoaderRoute: typeof MattersIdDeadlinesRouteImport
      parentRoute: typeof MattersIdRoute
    }
    '/intake/$id/ai-review': {
      id: '/intake/$id/ai-review'
      path: '/intake/$id/ai-review'
      fullPath: '/intake/$id/ai-review'
      preLoaderRoute: typeof IntakeIdAiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MattersIdRouteChildren {
  MattersIdDeadlinesRoute: typeof MattersIdDeadlinesRoute
  MattersIdDocumentsRoute: typeof MattersIdDocumentsRoute
  MattersIdNotesRoute: typeof MattersIdNotesRoute
  MattersIdOffersRoute: typeof MattersIdOffersRoute
  MattersIdTasksRoute: typeof MattersIdTasksRoute
  MattersIdTimelineRoute: typeof MattersIdTimelineRoute
  MattersIdIndexRoute: typeof MattersIdIndexRoute
}

const MattersIdRouteChildren: MattersIdRouteChildren = {
  MattersIdDeadlinesRoute: MattersIdDeadlinesRoute,
  MattersIdDocumentsRoute: MattersIdDocumentsRoute,
  MattersIdNotesRoute: MattersIdNotesRoute,
  MattersIdOffersRoute: MattersIdOffersRoute,
  MattersIdTasksRoute: MattersIdTasksRoute,
  MattersIdTimelineRoute: MattersIdTimelineRoute,
  MattersIdIndexRoute: MattersIdIndexRoute,
}

const MattersIdRouteWithChildren = MattersIdRoute._addFileChildren(
  MattersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiReviewRoute: AiReviewRoute,
  CommandCenterRoute: CommandCenterRoute,
  DeadlinesRoute: DeadlinesRoute,
  DocumentsRoute: DocumentsRoute,
  FirmUsersRoute: FirmUsersRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  TasksRoute: TasksRoute,
  MattersIdRoute: MattersIdRouteWithChildren,
  IntakeIndexRoute: IntakeIndexRoute,
  MattersIndexRoute: MattersIndexRoute,
  IntakeIdAiReviewRoute: IntakeIdAiReviewRoute,
  IntakeIdIndexRoute: IntakeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
